version: '3.7'

services:
    ytproxy:
        image: '1337kavin/ytproxy:latest'
        restart: always
        user: '33:33'
        volumes:
            - '/var/run/ytproxy/:/app/socket'
        networks:
            host: {}
networks:
    host: {}
